name: Metrics
on:
  schedule:
    - cron: '0 0 * * 1'
  workflow_dispatch:
  push:
    branches:
      - main
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          
          filename: metrics.svg
          user: litarussell
          template: classic
          base: header, activity, community, repositories, metadata
          config_timezone: Asia/Shanghai
          config_twemoji: yes
          plugin_lines: yes
